config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :photos
  resources :users, :only => [:new, :create, :index]
  resources :logins, :only => [:new, :create, :destroy]
  resources :problems, :only => [:new, :show, :index, :create] do
    member do
      put 'solved'
    end
    resources :notes, :only => [:create]
  end

  mount Sidekiq::Web => '/sidekiq'
  root 'problems#index'
  delete 'logout' => 'logins#destroy'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem

  validates :text, presence: true
  validates :user_id, presence: true
  validates :problem_id, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => {:large => "640x480>",
                                        :medium => "480x320>",
                                        :thumb => "200x200#"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  default_scope -> { order('created_at ASC') }

  validates :description, presence: true
  validates :attempt, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :problems
  has_many :notes

  validates :name, presence: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: /\A[\w\-\.]+@[\w\-\.]+\Z/,
            message: 'must be a valid email address' }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include LoginsHelper

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login(user)
      flash[:notice] = "You've successfully logged in."
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @problem = Problem.find(params[:problem_id])
    @note = @problem.notes.build(note_params)
    @note.user = current_user

    respond_to do |format|
      format.html do
        if @note.save
          # UserMailer.note_update_email(current_user, @problem).deliver
          flash.now[:notice] = 'Answered!'
        else
          flash.now[:notice] = 'Your answer is invalid.'
        end
        redirect_to @problem
      end

      format.js do
        if @note.save
          render :create, status: :created
        else
          render nothing: true, status: :bad_request
        end
      end
    end
  end

  private

  def note_params
    params.require(:note).permit(:text)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def new
    @problem = Problem.new
  end

  def create
    @problem = current_user.problems.build(problem_params)
    if @problem.save
      # UserMailer.create_problem_email(current_user, @problem).deliver
      flash[:success] = 'Your problem has been posted for solving.'
      redirect_to problem_path(@problem)
    else
      flash[:error] = 'There was a problem with your problem. Seriously.'
      render :new
    end
  end

  def show
    @problem = Problem.find(params[:id])
    @notes = @problem.notes
    @note = Note.new
  end

  def index
    @problem_where = Problem.where(solved: false)
    @problems = @problem_where.paginate(page: params[:page], per_page: 5)
  end

  def solved
    @problem = Problem.find(params[:id])
    @problem.update_attributes(solved: true)
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js do
        render :solved, status: 200
      end
    end
  end

  private

  def problem_params
    params.require(:problem).permit(:description, :attempt)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User Created'
      redirect_to new_login_path
    else
      flash[:error] = 'There was a problem creating your account.'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_getting_started.html.erb
<p></p>
<p>We hope you enjoy using <b>Mo' Problems</b> as much as we enjoyed creating it! Here’s a quick rundown of how it works:
</p>
<table>
  <tr>
    <td>
      <div class="icon">
        <i class="fa fa-question fa-4x" ></i>
      </div>
    </td>
    <td>
      <div class="explain">
        Post a <b>Problem</b> you’re having and what you’ve tried to do to solve it so far.
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="icon">
        <i class="fa fa-envelope-o fa-4x"></i>
      </div>
    </td>
    <td>
      <div class="explain">
        We’ll email you a link to your Problem page after it’s been successfully submitted.
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="icon">
        <i class="fa fa-users fa-4x"></i>
      </div>
    </td>
    <td>
      <div class="explain">
        Other users can leave <b>Notes</b> about your Problem with suggested solutions. (We’ll email you every time someone leaves a Note.)
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="icon">
        <i class="fa fa-thumbs-up fa-4x"></i>
      </div>
    </td>
    <td>
      <div class="explain">
        Once you’ve found a solution to your Problem, let us know! (Your Problem will no longer be displayed on the site.)
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="icon">
        <i class="fa fa-smile-o fa-4x"></i>
      </div>
    </td>
    <td>
      <div class="explain">
        Return the favor! Help other folks solve their Problems by leaving your own Notes.
      </div>
    </td>
  </tr>
</table>

app/views/layouts/_topnav.erb
<div class="topnav">
  <ul id="navlist">
    <li>
      <%= link_to 'All Problems', root_path %>
    </li>
    <li> Sign Up
      <!--<#= link_to "Sign Up", new_user_path %>-->
    </li>
    <!--<# if logged_in? == nil %>-->
      <li class="active"> Login
        <!--<#= link_to "Login", new_login_path %>-->
      </li>
    <!--<# end %>
    <# if logged_in? %>-->
      <li>
        <span class="current_user">
          Logged in as <b>Some Unidentified Human</b>
          <!--<#= current_user.name %>-->
        </span>
      </li>
      <li> Logout
        <!--<#= link_to "Logout", login_destroy_path, :method => :delete %>-->
      </li>
    <!--<# end %>-->
  </ul>
</div>

app/views/layouts/_topnav.html.erb
<div class="topnav">
  <ul id="navlist">
    <li>
      <%= link_to 'All Problems', root_path %>
    </li>
    <li>
      <%= link_to 'New Problem', new_problem_path %>
    </li>
    <li>
      <%= link_to 'All Photos', photos_path %>
    </li>
    <li>
      <%= link_to 'New Photo', new_photo_path %>
    </li>
    <% if logged_in? %>
      <!--want to set it so getting started partial gets a link when the user logs in-->
      <li>
        <%= link_to "Getting Started", users_path %>
      </li>
      <li>
        <span class="current_user">
          Logged in as
          <b><%= current_user.name %></b>
        </span>
      </li>
      <li>
        <%= link_to "Log out", logout_path, :method => :delete %>
      </li>
    <% else %>
      <li class="active">
        <%= link_to "Log in", new_login_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/topnav" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/logins/_login_form.html.erb
<%= form_for(:session, url: logins_path) do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.button :submit, class: "btn btn-large btn-success" %>

<% end %>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/destroy.html.erb
<h1>Logins#destroy</h1>
<p>Find me in app/views/logins/destroy.html.erb</p>

app/views/logins/new.html.erb
<div class="content">
  <p></p>
  <div class="formwrap">
    <h2>Log in</h2>
    <h4>(or <%= link_to "register for a new account", new_user_path %>)</h4>
    <%= render "logins/login_form" %>
  </div>
</div>

app/views/notes/_note.html.erb
    <div class="tan" id="<%= note.persisted? ? dom_id(note) : "note-new" %>">
      <ul id="list">
        <li><b><%= note.text %></b></li>
        <li><span class="asked_by"><%= "Submitted by #{note.user.name} #{note.created_at.strftime("on %m/%d/%Y at %I:%M%p")}" %> </span></li>
      </ul>
    </div>

app/views/notes/_note_form.html.erb
<% if logged_in? %>
  <h3 class="dark">Create a new Note</h3>
  <%= form_for @note, url: problem_notes_path(@problem.id), remote: true do |f| %>
    <%= f.text_area :text, :placeholder => "Add your Note here" %>
    <%= button_tag 'Submit' %>
  <% end %>

<% else %>
  <%= link_to 'Please log in to leave a Note for this Problem', new_login_path %>
<% end %>

app/views/notes/create.js.erb
$("#notes").append("<%= j render(@note) %>");
$("#<%= dom_id(@note) %>").effect("highlight", {color: '#AAA68B'}, 900);
$("#note_text").val("")

app/views/photos/index.html.erb
<div class="content">
  <p></p>
  <h2>Photo Album</h2>
  <p>Where you'll find all our great user submissions.</p>
  <div class="photo_wrap">
    <div class="row">
      <ul class="small-block-grid-3">
        <% @photos.each do |photo| %>
          <li><%= link_to image_tag(photo.image.url(:thumb)), photo %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="content">
  <p></p>
  <h2>Submit a Photo</h2>
  <p>Because seeing is believing.</p>
  <div class="negative_formwrap">
    <div class="row">
      <div class="large-12 columns">
        <%= simple_form_for @photo do |f| %>
          <%= f.text_area :caption, placeholder: "Please provide a caption for your photo"%>
          <%= f.file_field :image %>
          <%= f.button :submit, class: "btn btn-large btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="content">
  <p></p>
  <h2><%= @photo.caption %></h2>
  <div class="photo_wrap">
    <div class="row">
      <div class="small-12 columns">
        <%= image_tag @photo.image.url(:medium) %>
      </div>
    </div>
  </div>
</div>

app/views/problems/_problem.html.erb
<div id="<%= dom_id(problem) %>">
  <div class="tan">
    <ul id="list">
      <li>
      <h4>
        <b><%= link_to problem.description, problem_path(problem) %></b>
        </h4>
      </li>
      <li><%= truncate( problem.attempt, length: 75, separator: ' ')%></li>
      <li>
        <span class="asked_by">Submitted by <%= problem.user.name %> <%= problem.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("on %m/%d/%Y at %I:%M%p") %>
        </span>
      </li>
      <li>
        <% if current_user == problem.user %>
        <p>
          <h6 class="dark">
            <%= link_to  solved_problem_path(problem),  method: :put, remote: true do%>
             <i class="fa fa-thumbs-up fa-2x"></i>
        <% end %>
          My problem has been solved
          </h5>
        </p>
      </li>
  <% end %>
    </ul>
  </div>
</div>

app/views/problems/_problem_form.html.erb
<div class="new_problem">
  <%= form_for @problem, :url => problems_path do |f| %>
    <%= f.text_field :description, placeholder: "Problem description" %><br>
    <%= f.text_area :attempt, placeholder: "What you've tried so far to solve the Problem" %><br>
    <%= f.button :submit, class: "btn btn-large btn-success" %>
  <% end %>
</div>

app/views/problems/index.html.erb
<div class="content">
  <p></p><h1>Mo' Problems</h1>
  . . . where collaboration ends frustration.
  <div class="gap">
  </div>
  <% if !logged_in? %>
    <%= render "layouts/getting_started" %>
  <% end %>
  <br>
  <h3 class="dark">Current Problems</h3>
  <div id="problems">
    <%= render @problems %>
  </div>
  <div class="paginate">
    <b><%= will_paginate @problems %></b>
  </div>
</div>

app/views/problems/new.html.erb
<div class="content">
  <% if logged_in? %>
    <p></p>
    <h2>Submit a Problem</h2>
    <p>Please provide a brief description of the problem and what you've tried to solve it so far.</p>
   <div class="formwrap">
     <%= render "problems/problem_form" %>
    </div>
  <% else %>
    <p></p>
      <div class="formwrap">
        <h2>Log in</h2>
        <h4>(or <%= link_to "register for a new account", new_user_path %>)</h4>
        <%= render "logins/login_form" %>
      </div>
<% end %>
</div>

app/views/problems/show.html.erb
<div class="content">
  <p><h2><%= @problem.description %></h2></p>
  <p><%= @problem.attempt %></p>
  <% if current_user == @problem.user %>
    <p>
      <h5 class="dark">
        <%= link_to  solved_problem_path(@problem),  method: :put, data: { confirm: "Are you sure this is solved?"} do%>
          <i class="fa fa-thumbs-up fa-2x"></i>
         <% end %>
         My problem has been solved
      </h5>
    </p>
  <% end %>
  <br>
  <h3 class="dark"><%= pluralize(@problem.notes.count, "Note") %></h3>
  <div class="notes_wrapper" id="notes">
    <%= render @notes %>
  </div>
  <br>
  <div class="formwrap">
    <%= render "notes/note_form" %>
  </div>
</div>

app/views/problems/solved.js.erb
$("#<%= dom_id(@problem) %>").remove();
//$("#<#= dom_id(@problem) %>").replaceWith("<#= j render(@problem) %>");

app/views/users/_register_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="negative_formwrap">
  <div class="row">
    <div class="small-12 columns">
      <div class="field">
        <%= f.label :name, nil, class: 'post_label' %><br>
        <%= f.text_field :name %>
      </div>
    </div>
  </div>
  <div class="large-12 columns">
    <div class="field">
      <%= f.label :email, nil, class: 'post_label' %><br>
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <div class="field">
        <%= f.label :password, nil, class: 'post_label' %><br>
        <%= f.password_field :password %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <div class="field">
        <%= f.label :password_confirmation, nil, class: 'post_label' %><br>
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
  </div>
</div>
  <div class="actions">
    <%= f.button :submit, class: "radius small" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="content">
  <p></p>
  <h2>Getting Started</h2>
  <%= render "layouts/getting_started" %>
</div>

app/views/users/new.html.erb
<div class="content">
  <p><h2>Register for a new account</h2></p>
    <%= render "users/register_form" %>
</div>